### ISSUE TITLE
Method for mapping over Spanned::node

### ISSUE THREAD

**Issue by connorskees** [kevinmehall/codemap#10]
I am finding that I have to destructure `codemap::Spanned` frequently in order to transform the node. 

A method on `codemap::Spanned` like this would really help me:

```rust
pub fn map_node<U, F: FnOnce(T) -> U>(self, op: F) -> Spanned<U>;
```

**Comment by kevinmehall** [comment]
Yeah, that sounds good. Want to submit a PR?
