### ISSUE TITLE
Add tests for codemap

### ISSUE THREAD

**Issue by pickfire** [kevinmehall/codemap#14]
```rust
mod foo {
    pub fn x(y: isize) { log(debug, y); }
    //~^ ERROR cannot find function `log` in this scope
    //~| ERROR cannot find value `debug` in this scope
    fn z(y: isize) { log(debug, y); }
    //~^ ERROR cannot find function `log` in this scope
    //~| ERROR cannot find value `debug` in this scope
}

fn main() { foo::z(10); } //~ ERROR function `z` is private
```

Example https://github.com/rust-lang/rust/blob/master/src/test/ui/export.rs

Maybe one could take code generation approach? Not sure how rust did that but it generates `.stderr` files to show the snapshot of the exact error.

**Comment by pickfire** [comment]
This exists as https://crates.io/crates/compiletest_rs

**Comment by pickfire** [comment]
But that only works for rust projects, sometimes it would be useful for non-rust projects to use codemap. I see this may be useful in https://github.com/connorskees/grass

**Comment by kevinmehall** [comment]
This library is just utilities for storing and manipulating spans, and does not have any error reporting to test. Maybe you're thinking of [codemap-diagnostic](https://github.com/kevinmehall/codemap-diagnostic/issues/1)? There are basic unit tests for the functionality of this library already, but please open a PR if you see a place to improve test coverage.
