### ISSUE TITLE
Panic when pointing at end of line when line has trailing whitespace with codemap / codemap-diagnostic 0.1

### ISSUE THREAD

**Issue by damienmg** [kevinmehall/codemap#2]
Hello,

I realize that this might be outside of the scope of the codemap package (I am using it to emit diagnostic on a whitespace sensitive language).

Because of https://github.com/kevinmehall/codemap/blob/master/src/lib.rs#L250, the end of line is trimmed which make the following code fails when trying to point to the end of line:

```rust
use codemap_diagnostic::{Emitter, ColorConfig, SpanLabel, Diagnostic, Level, SpanStyle};
use codemap::CodeMap;

#[test]
fn test_not_panic_eol() {
    let mut codemap = CodeMap::new();
    let content = " \n\n";
    let file = codemap.add_file("<test>".to_owned(), content.to_owned());
    let sl = SpanLabel {
        span: file.span.subspan(1, 1),
        style: SpanStyle::Primary,
        label: Some("label".to_owned()),
    };
    let v = [Diagnostic {
        level:Level::Error,
        message: "Message".to_owned(),
        code: None,
        spans: vec![sl]
    }];
    Emitter::stderr(ColorConfig::Always, Some(&codemap)).emit(&v);
}
```

**Comment by damienmg** [comment]
(Also I haven't investigated why the trimming is necessary)

**Comment by kevinmehall** [comment]
Definitely within the scope of what this library is intended for. I think the `.trim_right()` was intended to strip the trailing newline character when getting the text of a line, but I've moved it to a more appropriate place and limited it to only strip `\r\n`.

**Comment by damienmg** [comment]
That was fast, thanks!
