### ISSUE TITLE
Make CodeMap::add_file take &self

### ISSUE THREAD

**Issue by nox** [kevinmehall/codemap#3]
I want to use `CodeMap` to own my source code and to be able to borrow from the code for items in the AST, but I can't do that given I sometimes need to add new input files and `CodeMap::add_file` takes `&mut self`.

The current `SourceMap` stuff in rustc takes a `&self` value for this operation.

https://doc.rust-lang.org/nightly/nightly-rustc/syntax/source_map/struct.SourceMap.html#method.load_file

**Comment by kevinmehall** [comment]
Could you expand on the limitation you're running into? `add_file` returns `Arc<File>` so the lifetime of the `File` (which owns the source code) is not tied to the lifetime of the `&mut` borrow of the `CodeMap`. On the other hand, borrowing a slice of source code out of that `Arc` to store in an AST would be problematic, but that's what a `Span` is for.

Making this method take `&self` would require internal mutability, which is less idiomatic and requires a choice between `RefCell` and `Mutex` in the library. Instead, you can make that choice and wrap the `CodeMap` in one of those yourself if required.

**Comment by nox** [comment]
Fair enough, I misread the docs on `SourceMap` anyway and what rustc currently does wouldn't help me anyway.

I thought of using `Span` but I wanted to be able to use `Cow<str>` out of the box with `Cow::Borrowed` representing string literals with no escape sequences. I'll do an ad-hoc type with 2 variants `Span` or `String`.

Thanks for the quick answer, I've yet to write any line of code but I like what you did with this crate and `codemap_diagnostics`.
