### ISSUE TITLE
Method for merging spans in place

### ISSUE THREAD

**Issue by connorskees** [kevinmehall/codemap#9]
Hello!

Do you think it would be possible and make sense to add something like
```rust
pub fn merge_in_place(&mut self, other: Span);
```
to the implementation of `Span`?

I can go ahead and make a pull request for this if you would like.

**Comment by kevinmehall** [comment]
I'm considering replacing `Span` and `Pos` with the types from the [text-size](https://docs.rs/text-size/) crate. Its equivalent of `merge` is `cover`, and similarly does not have any `&mut self` methods.

As a `Copy` type, you're probably better off just writing `x = x.merge(y)` over adding in-place variants of every method. I was wondering if there was a naming convention for this kind of in-place vs functional pair of methods, but it doesn't seem common in Rust libraries.
